version: "3.9"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vismatimeline
    volumes:
      - ./src/database/initialize.sql:/docker-entrypoint-initdb.d/init.sql

  react-app:
    build:
      context: visma/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true